on: [push]

jobs:
    test:
      runs-on: ubuntu-18.04
      name: A test job
      steps:
        # To use this repository's private action,
        # you must check out the repository
        - name: Checkout
          uses: actions/checkout@v2
        - name: Hello world action step
          uses: ./